# Arduino_LEDs
set_property PACKAGE_PIN W23        [get_ports LED[0]]
set_property IOSTANDARD LVCMOS33    [get_ports LED[0]]
set_property PACKAGE_PIN AB26       [get_ports LED[1]]
set_property IOSTANDARD LVCMOS33    [get_ports LED[1]]
set_property PACKAGE_PIN Y25        [get_ports LED[2]]
set_property IOSTANDARD LVCMOS33    [get_ports LED[2]]
set_property PACKAGE_PIN AA23       [get_ports LED[3]]
set_property IOSTANDARD LVCMOS33    [get_ports LED[3]]
set_property PACKAGE_PIN Y23        [get_ports LED[4]]
set_property IOSTANDARD LVCMOS33    [get_ports LED[4]]
set_property PACKAGE_PIN Y22        [get_ports LED[5]]
set_property IOSTANDARD LVCMOS33    [get_ports LED[5]]
set_property PACKAGE_PIN AE21       [get_ports LED[6]]
set_property IOSTANDARD LVCMOS33    [get_ports LED[6]]
set_property PACKAGE_PIN AF24       [get_ports LED[7]]
set_property IOSTANDARD LVCMOS33    [get_ports LED[7]]