# Buttons x
set_property PACKAGE_PIN V17        [get_ports BTNX[0]]
set_property IOSTANDARD LVCMOS18    [get_ports BTNX[0]]
set_property PACKAGE_PIN W18        [get_ports BTNX[1]]
set_property IOSTANDARD LVCMOS18    [get_ports BTNX[1]]
set_property PACKAGE_PIN W19        [get_ports BTNX[2]]
set_property IOSTANDARD LVCMOS18    [get_ports BTNX[2]]
set_property PACKAGE_PIN W15        [get_ports BTNX[3]]
set_property IOSTANDARD LVCMOS18    [get_ports BTNX[3]]
set_property PACKAGE_PIN W16        [get_ports BTNX[4]]
set_property IOSTANDARD LVCMOS18    [get_ports BTNX[4]]
# Buttons y
set_property PACKAGE_PIN V18        [get_ports BTNY[0]]
set_property IOSTANDARD LVCMOS18    [get_ports BTNY[0]]
set_property PACKAGE_PIN V19        [get_ports BTNY[1]]
set_property IOSTANDARD LVCMOS18    [get_ports BTNY[1]]
set_property PACKAGE_PIN V14        [get_ports BTNY[2]]
set_property IOSTANDARD LVCMOS18    [get_ports BTNY[2]]
set_property PACKAGE_PIN W14        [get_ports BTNY[3]]
set_property IOSTANDARD LVCMOS18    [get_ports BTNY[3]]